### ISSUE TITLE
Sanity locks up after detecting Canon scanner

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/sanity#12]
Canon MX320
Sanity auto detects USB connected scanner then locks up
Attaching debugger to Sanity brings up error message (see attached screenshot)
Debugger report attached
![sanity_error](https://cloud.githubusercontent.com/assets/13264393/22003856/1c4f5e8a-dc14-11e6-839c-812dbb4f394d.png)
[Sanity-465-debug-17-01-2017-12-04-34.report.txt](https://github.com/diversys/sanity/files/709730/Sanity-465-debug-17-01-2017-12-04-34.report.txt)

**Comment by diversys** [comment]
You can press Skip in this dialog, Debugger is just looking for a debug version of libjpeg (it's part of a separated package https://github.com/haikuports/haikuports/blob/master/media-libs/jpeg/jpeg-9b.recipe#L68) which is in turn a dependency of Translation Kit (JPEGTranslator). 

You would then need to click every Running thread followed by Debug and take pics of what's inside of the upper right view of Debugger (e.g. view with Frame, IP and Function columns).

**Comment by Vidrep** [comment]
Attached are the debug screenshots as you instructed. Would it be worthwhile to build and install the jpeg-9b package from haikuports?

![thread_1253](https://cloud.githubusercontent.com/assets/13264393/22032889/93d26d0a-dca3-11e6-9f5d-4508b55223db.png)
![thread_1258](https://cloud.githubusercontent.com/assets/13264393/22032893/96b3bdc6-dca3-11e6-9e03-87e1476f5c6b.png)
![thread_1492](https://cloud.githubusercontent.com/assets/13264393/22032894/99689e6a-dca3-11e6-8a45-614c050abea2.png)
![thread_1727](https://cloud.githubusercontent.com/assets/13264393/22032900/9c7a599a-dca3-11e6-8440-e2c4be716f3a.png)

**Comment by diversys** [comment]
It looks like the very last image is the one we needed (all the rest are just waiting for BLooper).
Could you please select it again and click Tools->Save debug report?

**Comment by Vidrep** [comment]
I have two Canon multifunction printers, both exhibiting the same issue.
According to the SANE Supported devices page (http://www.sane-project.org/sane-mfgs.html#Z-CANON)
the MP210 is "complete", while the MX320 is "untested; Same protocol as Pixma Generation 3? Testers needed!". I'll contact the SANE project developers and provide test info for that unit.
I ran the debugger and saved the report as instructed, on both scanners.
I have attached screenshots of the debugged thread and the corresponding reports.
![mp-210_team_1707_transferworker](https://cloud.githubusercontent.com/assets/13264393/22044602/cd8feb4c-dcd2-11e6-9840-cb20bd7a68f9.png)
[MP210_Sanity-1217-debug-18-01-2017-11-25-34.report.txt](https://github.com/diversys/sanity/files/712620/MP210_Sanity-1217-debug-18-01-2017-11-25-34.report.txt)
![mx320_team_931_transferworker](https://cloud.githubusercontent.com/assets/13264393/22044624/d845ec76-dcd2-11e6-9b27-daf2eee1373b.png)
[MX320_Sanity-454-debug-18-01-2017-11-20-07.report.txt](https://github.com/diversys/sanity/files/712621/MX320_Sanity-454-debug-18-01-2017-11-20-07.report.txt)

I am available most days to discuss further, if needed, on the #haiku IRC channel.

**Comment by phoudoin** [comment]
Sounds more like an issue with libusb port, no?

**Comment by diversys** [comment]
Same thought here. It's probably better to move this issue over to haikuports.

**Comment by Vidrep** [comment]
I'm just pasting the results of "scanimage --listdevices" after-the-fact so we have a record.

Welcome to the Haiku shell.

~> scanimage --list-devices
device `pixma:04A91721_71DF23' is a CANON Canon PIXMA MP210 multi-function peripheral
~> 

Welcome to the Haiku shell.

~> scanimage --list-devices
device `pixma:04A91736_15644C' is a CANON Canon PIXMA MX320 multi-function peripheral
~> 

Where do we go from here?
