### ISSUE TITLE
Sanity fails to build on x86_gcc5 hybrid

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/sanity#13]
Adding a secondary arch will enable the app to start building:
SECONDARY_ARCHITECTURES="x86_gcc2 !x86"

However, once the build process starts it fails with a series of errors:

SaneUtils.cpp: In function 'SANE_Int GetSaneInt(SANE_Handle, const char*)':
SaneUtils.cpp:21:43: error: 'strcmp' was not declared in this scope
    if (opt->name && strcmp(opt->name, name) == 0) {
                                           ^
SaneUtils.cpp: In function 'float GetSaneFloat(SANE_Handle, const char*)':
SaneUtils.cpp:56:43: error: 'strcmp' was not declared in this scope
    if (opt->name && strcmp(opt->name, name) == 0) {
                                           ^
g++ -c Sanity.cpp -iquote./  -iquote./  -iquoteobjects/   -O3    -o "objects/Sanity.o"
SaneUtils.cpp: In function 'float GetSaneMaxFloat(SANE_Handle, const char*)':
SaneUtils.cpp:91:43: error: 'strcmp' was not declared in this scope
    if (opt->name && strcmp(opt->name, name) == 0) {
                                           ^
SaneUtils.cpp: In function 'float GetSaneMinFloat(SANE_Handle, const char*)':
SaneUtils.cpp:126:43: error: 'strcmp' was not declared in this scope
    if (opt->name && strcmp(opt->name, name) == 0) {
                                           ^
SaneUtils.cpp: In function 'void SetSaneInt(SANE_Handle, const char*, SANE_Int)':
SaneUtils.cpp:161:43: error: 'strcmp' was not declared in this scope
    if (opt->name && strcmp(opt->name, name) == 0) {
                                           ^
SaneUtils.cpp: In function 'void SetSaneFloat(SANE_Handle, const char*, float)':
SaneUtils.cpp:187:43: error: 'strcmp' was not declared in this scope
    if (opt->name && strcmp(opt->name, name) == 0) {
                                           ^
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects/SaneUtils.o' failed
make: *** [objects/SaneUtils.o] Error 1
make: *** Waiting for unfinished jobs....
[Errno -2147459069] No such file or directory: '/boot/home/haikuports/haiku-apps/sanity/work-x86_gcc2-0.6'
Error: Build has failed - stopping.
~/haikuports>

**Comment by diversys** [comment]
Should be fixed in f602688.

**Comment by Vidrep** [comment]
Confirmed working on x86_gcc5 hybrid arch.
Thanks for the quick fix!
